name: Backend
on:
  push:
    paths:
      - packages/ob-backend/**
      - packages/ob-kube/backend/**
      - .github/**
      - package.json
    branches:
      - main

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: Check out repository code.
              uses: actions/checkout@v2

            - name: Install Node.js.
              uses: actions/setup-node@v2
              with:
                  node-version: '18.12'

            - name: Cache Yarn cache.
              uses: c-hive/gha-yarn-cache@v2

            - name: Install project dependencies.
              run: yarn --prefer-offline  --frozen-lockfile
              
            - name: Run Tests.
              env:
                  ENVIRONMENT: test
              run: echo "OK"
  
    build:
        needs: test
        runs-on: ubuntu-latest
        steps:
            - name: Check out repository code.
              uses: actions/checkout@v2

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3
              with:
                buildkitd-flags: --debug
            
            - name: Login to GitHub Container Registry
              uses: docker/login-action@v2
              with:
                registry: ghcr.io
                username: ${{ github.repository_owner }}
                password: ${{ secrets.GITHUB_TOKEN }}

            - name: Build and push the Docker image
              uses: docker/build-push-action@v5
              with:
                push: true
                context: .
                file: ./packages/ob-backend/Dockerfile
                platforms: linux/amd64,linux/arm64/v8
                tags: |
                  ghcr.io/obudynku/ob-backend:latest
                  ghcr.io/obudynku/ob-backend:${{ github.sha }}
                cache-from: type=gha
                cache-to: type=gha,mode=max