name: Frontend
"on":
  push:
    paths:
      - packages/ob-frontend/**
      - packages/ob-kube/frontend/**
      - .github/**
      - package.json
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code.
        uses: actions/checkout@v2
      - name: Install Node.js.
        uses: actions/setup-node@v2
        with:
          node-version: "18.12"
      - name: Cache Yarn cache.
        uses: c-hive/gha-yarn-cache@v2
      - name: Install project dependencies.
        run: yarn --prefer-offline  --frozen-lockfile
      - name: Run Tests.
        env:
          ENVIRONMENT: test
        run: echo "OK"
  build:
    needs: test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform:
          - linux/amd64
          - linux/arm64
    steps:
      - name: Check out repository code.
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: "${{ github.repository_owner }}"
          password: "${{ secrets.GITHUB_TOKEN }}"
      - name: Build and push the Docker image
        uses: docker/build-push-action@v5
        with:
          push: true
          context: .
          file: ./packages/ob-frontend/Dockerfile
          platforms: ${{ matrix.platform }}
          buildkitd-flags: "--debug"
          tags: |
            ghcr.io/obudynku/ob-frontend:latest
            ghcr.io/obudynku/ob-frontend:${{ github.sha }}
